### ISSUE TITLE
Request: Auto-create .aws folder if not existent

### ISSUE THREAD

**Issue by larsveelaert** [glnds/masl#6]
After a setup & execution on Windows no error was thrown if the 'credentials' file could not be placed in the ~/.aws folder (because it did not exist yet).
Would it be possible to check it's existence / create the .aws folder?

#GreatestFan #MaslFTW

**Comment by siwyd** [comment]
@larsveelaert Hah, didn't see you had a branch, thought I'd throw in a quick fix for you, but never mind my branch. @glnds Some weird behaviour with the inifile SaveTo it seems. The not logging of the error is weird though, because there's a log.Fatal(err) line in there...

**Comment by glnds** [comment]
@siwyd i feel the urge for a first unit test :)
